"""add_friendship_table

Revision ID: 21826daed1ec
Revises: 6f280f33d11b
Create Date: 2026-01-06 16:11:03.174834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21826daed1ec'
down_revision: Union[str, Sequence[str], None] = '6f280f33d11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_user_friend')
    )
    op.drop_table('message_viewers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_viewers',
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_viewers_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_viewers_user_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', 'user_id', name=op.f('message_viewers_pkey'))
    )
    op.drop_table('friendships')
    # ### end Alembic commands ###
