"""modify_file_column_to_jsonb

Revision ID: 5c58e845e443
Revises: 6ca16c845bb4
Create Date: 2026-01-06 15:30:12.011504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c58e845e443'
down_revision: Union[str, Sequence[str], None] = '6ca16c845bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('messages', 'file_url')
    op.drop_column('messages', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'file')
    # ### end Alembic commands ###
