"""add_last_read_message_id_column_to_conversation_members_table

Revision ID: 6f280f33d11b
Revises: 5c58e845e443
Create Date: 2026-01-06 15:48:36.217778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f280f33d11b'
down_revision: Union[str, Sequence[str], None] = '5c58e845e443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_members', sa.Column('last_read_message_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'conversation_members', 'messages', ['last_read_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.drop_column('conversation_members', 'last_read_message_id')
    # ### end Alembic commands ###
