"""init

Revision ID: 96fd7d9aa087
Revises: d0ae8f5bf422
Create Date: 2026-01-06 10:23:30.636194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '96fd7d9aa087'
down_revision: Union[str, Sequence[str], None] = 'd0ae8f5bf422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


message_type_enum = ENUM(
    "text", "image", "file",
    name="messagetype"
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    message_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('messages', sa.Column('type', message_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    message_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
