"""add_foreignkey

Revision ID: a60f304acb8c
Revises: 653ea6763234
Create Date: 2026-01-07 15:54:11.827799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60f304acb8c'
down_revision: Union[str, Sequence[str], None] = '653ea6763234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'messages', ['last_message_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
