"""add_foreignkey

Revision ID: d0ae8f5bf422
Revises: 931ba72490e0
Create Date: 2026-01-06 09:31:32.227073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ae8f5bf422'
down_revision: Union[str, Sequence[str], None] = '931ba72490e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'categories', 'categories', ['pid'], ['id'])
    op.create_foreign_key(None, 'conversation_admins', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'conversation_admins', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'conversation_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'conversation_members', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'messages', ['last_message_id'], ['id'])
    op.create_foreign_key(None, 'message_viewers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'message_viewers', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'message_viewers', type_='foreignkey')
    op.drop_constraint(None, 'message_viewers', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.drop_constraint(None, 'conversation_admins', type_='foreignkey')
    op.drop_constraint(None, 'conversation_admins', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    # ### end Alembic commands ###
